name: codependence-monorepo

on:
  push:
    branches: [master, update-dependencies]
  pull_request:
    branches: [master, update-dependencies]
  repository_dispatch:
    types: [codependence_update]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
        env:
          CI: true
